version: "2"

run:
  timeout: 10m
  tests: true
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - fatcontext
    - gocheckcompilerdirectives
    - gocritic
    - gomoddirectives
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - nilnesserr
    - nilnil
    - nolintlint
    - nosprintfhostport
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - thelper
    - unconvert
    - unparam
    - unused
    - wastedassign

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
