package main

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/cssbruno/gowdk"
	"github.com/cssbruno/gowdk/internal/appgen"
	"github.com/cssbruno/gowdk/internal/auditsarif"
	"github.com/cssbruno/gowdk/internal/auditschema"
	"github.com/cssbruno/gowdk/internal/auditspec"
	"github.com/cssbruno/gowdk/internal/buildgen"
	"github.com/cssbruno/gowdk/internal/diagnostics"
	"github.com/cssbruno/gowdk/internal/gwdkir"
	"github.com/cssbruno/gowdk/internal/lang"
	"github.com/cssbruno/gowdk/internal/securitymanifest"
)

const auditUsage = "usage: gowdk audit [--config <file>] [--env-file <file>] [--module <name>] [--ssr] [--json] [--sarif[=<file>]] [--diff <previous-report>] [--schema[=report|security]] [--emit-tests[=<file>]] [--check-tests[=<file>]] [--force] [--run] [--run-timeout=<duration>] [files...]"

const (
	auditGeneratedMarker         = "// Code generated by gowdk audit --emit-tests; DO NOT EDIT.\n"
	auditGeneratedMetadataPrefix = "// gowdk:audit-generated "
)

// auditReport is the gowdk audit result: the derived security posture plus the
// findings from evaluating the built-in baseline and declared policies against
// it.
type auditReport struct {
	Version       int                               `json:"version"`
	Schema        string                            `json:"schema"`
	Tool          auditToolMetadata                 `json:"tool"`
	PolicyDigest  string                            `json:"policyDigest"`
	PostureDigest string                            `json:"postureDigest"`
	BuildMode     string                            `json:"buildMode"`
	Target        auditTargetMetadata               `json:"target"`
	History       auditHistoryMetadata              `json:"history"`
	Status        string                            `json:"status"`
	Summary       auditSummary                      `json:"summary"`
	Posture       auditPostureSummary               `json:"posture"`
	Waivers       []auditWaiverRecord               `json:"waivers,omitempty"`
	Findings      []auditspec.Finding               `json:"findings"`
	Diff          *auditDiff                        `json:"diff,omitempty"`
	Manifest      securitymanifest.SecurityManifest `json:"manifest"`
}

// auditWaiverRecord records one applied waiver so every suppression is visible
// provenance in the JSON audit output, not just a silently missing finding.
type auditWaiverRecord struct {
	Code          string `json:"code"`
	Target        string `json:"target,omitempty"`
	Owner         string `json:"owner,omitempty"`
	Justification string `json:"justification,omitempty"`
	Expires       string `json:"expires,omitempty"`
	Ticket        string `json:"ticket,omitempty"`
	DigestScope   string `json:"digestScope,omitempty"`
	Source        string `json:"source,omitempty"`
}

// auditPostureSummary counts the module's security obligations by evidence state
// so a human or CI can see, at a glance, how much of the posture gowdk proves
// statically versus what is app-owned and unverified.
type auditPostureSummary struct {
	Obligations        int            `json:"obligations"`
	Evidence           map[string]int `json:"evidence"`
	UnverifiedAppOwned int            `json:"unverifiedAppOwned"`
}

type auditToolMetadata struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

type auditTargetMetadata struct {
	BuildMode string `json:"buildMode"`
}

type auditHistoryMetadata struct {
	Mode string `json:"mode"`
}

type auditSummary struct {
	Routes    int `json:"routes"`
	Endpoints int `json:"endpoints"`
	Contracts int `json:"contracts"`
	Errors    int `json:"errors"`
	Warnings  int `json:"warnings"`
	Info      int `json:"info"`
	Waived    int `json:"waived"`
}

type auditCommandOptions struct {
	EmitTests  bool
	CheckTests bool
	RunTests   bool
	Force      bool
	TestPath   string
	RunTimeout time.Duration
	// Schema, when set, prints a published JSON Schema ("report" or "security")
	// and exits without evaluating a project.
	Schema string
	// SARIF emits SARIF 2.1.0 for GitHub code scanning. SARIFPath, when set,
	// writes SARIF to that file while normal output still goes to stdout.
	SARIF     bool
	SARIFPath string
	// DiffPath, when set, compares the current findings against a previous JSON
	// report and gates only newly introduced findings.
	DiffPath string
}

// gowdk audit exit codes form the documented CI contract. The values are stable;
// CI gates should switch on them rather than on "non-zero".
const (
	auditExitOK             = 0 // no error findings (clean or warning-only)
	auditExitToolFailure    = 1 // internal/tool failure (default for any unexpected error)
	auditExitInvalidSource  = 2 // source or policy could not be evaluated
	auditExitErrorFindings  = 3 // one or more error-severity findings
	auditExitRuntimeFailure = 4 // generated runtime audit test failed or timed out (--run)
)

type auditExitError struct {
	errors int
	code   int
}

func (err auditExitError) Error() string {
	return fmt.Sprintf("audit found %d error finding(s)", err.errors)
}

// ExitCode implements the CLI exit-code contract for finding-driven failures.
func (err auditExitError) ExitCode() int {
	if err.code != 0 {
		return err.code
	}
	return auditExitErrorFindings
}

func (auditExitError) SilentCLIError() {}

// exitCodeError carries a specific process exit code for a non-finding failure
// (for example invalid source) while still printing its message.
type exitCodeError struct {
	code int
	err  error
}

func (err exitCodeError) Error() string { return err.err.Error() }

func (err exitCodeError) Unwrap() error { return err.err }

func (err exitCodeError) ExitCode() int { return err.code }

// audit derives the security posture from validated IR, evaluates the baseline
// policy against it, and reports findings. It is the full report surface
// (posture JSON, declared policies, optional runtime tests) and exits non-zero
// when any error-severity finding exists so it can gate CI. gowdk build runs the
// same baseline as a production gate (see enforceBuildSecurityAudit); this
// command stays available for explicit reports and non-production checks.
func audit(args []string) error {
	auditOptions, projectArgs, err := parseAuditCommandOptions(args)
	if err != nil {
		return err
	}
	if auditOptions.Schema != "" {
		return printAuditSchema(auditOptions.Schema)
	}
	options, paths, err := loadCommandInputs(projectArgs, "audit", true)
	if err != nil {
		return err
	}

	checked, diags := lang.CheckFilesWithOptions(options.Config, paths, lang.CheckOptions{ProjectRoot: options.ProjectRoot})
	for _, diagnostic := range diags {
		fmt.Fprintln(os.Stderr, diagnostic.String())
	}
	if diags.HasErrors() {
		return exitCodeError{code: auditExitInvalidSource, err: fmt.Errorf("audit failed: source has validation errors")}
	}

	ir := checked.IR
	if err := linkIRContractReferences(&ir, options.ProjectRoot); err != nil {
		return err
	}

	// Relativize source locations to the project root so the posture — and the
	// digests, findings, and emitted tests derived from it — are identical
	// regardless of where the project is checked out.
	manifest := securitymanifest.Build(options.Config, ir).Relativize(options.ProjectRoot)
	declared := auditspec.PoliciesFromIR(ir.AuditSpecs)
	policies := relativizeAuditPolicies(auditspec.ComposeBaseline(declared), options.ProjectRoot)
	waiverCtx := auditspec.WaiverContext{
		PolicyDigest:  auditPolicyDigest(policies),
		PostureDigest: auditPostureDigest(manifest),
	}
	findings := auditspec.EvaluateWithWaivers(manifest, policies, waiverCtx)
	testFindings, err := handleAuditTests(auditOptions, options, ir, manifest)
	if err != nil {
		return err
	}
	findings = append(findings, testFindings...)
	findings = auditspec.EnrichFindings(findings)
	auditspec.SortFindings(findings)
	report := buildAuditReport(options, manifest, findings, policies)

	if auditOptions.DiffPath != "" {
		previous, err := loadPreviousAuditReport(auditOptions.DiffPath)
		if err != nil {
			return exitCodeError{code: auditExitInvalidSource, err: err}
		}
		diff := computeAuditDiff(previousReportBaseline(previous, auditOptions.DiffPath), previous.Findings, report.Findings)
		report.Diff = &diff
	}

	if err := emitAuditReport(report, options, auditOptions); err != nil {
		return err
	}
	return auditExitResult(report)
}

// printAuditSchema prints a published JSON Schema and exits. It is the CLI face
// of the versioned contract so CI can fetch the exact schema the running tool
// validates against (gowdk audit --schema[=report|security]).
func printAuditSchema(name string) error {
	payload, err := auditschema.Schema(auditschema.Name(name))
	if err != nil {
		return exitCodeError{code: auditExitInvalidSource, err: err}
	}
	fmt.Println(strings.TrimRight(string(payload), "\n"))
	return nil
}

// emitAuditReport writes the report in the selected formats. SARIF goes to a
// sidecar file (when --sarif=<file>) alongside the normal stdout output, or to
// stdout as the sole payload (bare --sarif). Otherwise JSON or human output goes
// to stdout.
func emitAuditReport(report auditReport, options cliOptions, auditOptions auditCommandOptions) error {
	if auditOptions.SARIF {
		payload, err := auditSARIFBytes(report)
		if err != nil {
			return err
		}
		if auditOptions.SARIFPath == "" {
			fmt.Println(string(payload))
			return nil
		}
		if err := os.WriteFile(auditOptions.SARIFPath, append(payload, '\n'), 0o644); err != nil {
			return err
		}
		fmt.Fprintf(os.Stderr, "wrote SARIF: %s\n", auditOptions.SARIFPath)
	}

	if options.JSON {
		payload, err := json.MarshalIndent(report, "", "  ")
		if err != nil {
			return err
		}
		fmt.Println(string(payload))
		return nil
	}
	printAuditReport(report)
	return nil
}

func auditSARIFBytes(report auditReport) ([]byte, error) {
	doc := auditsarif.FromFindings(report.Findings, auditsarif.Options{
		ToolName:       "gowdk audit",
		ToolVersion:    version,
		InformationURI: "https://github.com/cssbruno/gowdk",
	})
	return json.MarshalIndent(doc, "", "  ")
}

// auditExitResult maps a report to the documented exit-code contract. With a
// diff, the gate is on newly introduced findings; otherwise it is on all error
// findings. A runtime audit-test failure takes precedence over a static policy
// error so CI can tell the two apart.
func auditExitResult(report auditReport) error {
	if report.Diff != nil {
		if report.Diff.IntroducedErrors > 0 {
			return auditExitError{errors: report.Diff.IntroducedErrors, code: auditErrorExitCode(report.Diff.Introduced)}
		}
		return nil
	}
	if report.Summary.Errors > 0 {
		return auditExitError{errors: report.Summary.Errors, code: auditErrorExitCode(report.Findings)}
	}
	return nil
}

func auditErrorExitCode(findings []auditspec.Finding) int {
	for _, finding := range findings {
		if finding.Suppression != nil || finding.Severity != diagnostics.SeverityError {
			continue
		}
		if finding.Code == "audit_test_failed" || finding.Code == "audit_test_timeout" {
			return auditExitRuntimeFailure
		}
	}
	return auditExitErrorFindings
}

func parseAuditCommandOptions(args []string) (auditCommandOptions, []string, error) {
	options := auditCommandOptions{TestPath: "gowdk_audit_test.go"}
	var projectArgs []string
	for index := 0; index < len(args); index++ {
		arg := args[index]
		switch {
		case arg == "--emit-tests":
			options.EmitTests = true
		case strings.HasPrefix(arg, "--emit-tests="):
			options.EmitTests = true
			options.TestPath = strings.TrimSpace(strings.TrimPrefix(arg, "--emit-tests="))
			if options.TestPath == "" {
				return options, nil, fmt.Errorf(auditUsage)
			}
		case arg == "--check-tests":
			options.CheckTests = true
		case strings.HasPrefix(arg, "--check-tests="):
			options.CheckTests = true
			options.TestPath = strings.TrimSpace(strings.TrimPrefix(arg, "--check-tests="))
			if options.TestPath == "" {
				return options, nil, fmt.Errorf(auditUsage)
			}
		case arg == "--force":
			options.Force = true
		case arg == "--run":
			options.RunTests = true
		case strings.HasPrefix(arg, "--run-timeout="):
			value := strings.TrimSpace(strings.TrimPrefix(arg, "--run-timeout="))
			duration, err := time.ParseDuration(value)
			if err != nil {
				return options, nil, fmt.Errorf("invalid --run-timeout %q: %w", value, err)
			}
			if duration <= 0 {
				return options, nil, fmt.Errorf("invalid --run-timeout %q: must be positive", value)
			}
			options.RunTimeout = duration
		case arg == "--schema":
			options.Schema = string(auditschema.AuditReport)
		case strings.HasPrefix(arg, "--schema="):
			options.Schema = strings.TrimSpace(strings.TrimPrefix(arg, "--schema="))
			if options.Schema == "" {
				return options, nil, fmt.Errorf(auditUsage)
			}
		case arg == "--sarif":
			options.SARIF = true
		case strings.HasPrefix(arg, "--sarif="):
			options.SARIF = true
			options.SARIFPath = strings.TrimSpace(strings.TrimPrefix(arg, "--sarif="))
			if options.SARIFPath == "" {
				return options, nil, fmt.Errorf(auditUsage)
			}
		case strings.HasPrefix(arg, "--diff="):
			options.DiffPath = strings.TrimSpace(strings.TrimPrefix(arg, "--diff="))
			if options.DiffPath == "" {
				return options, nil, fmt.Errorf(auditUsage)
			}
		case arg == "--diff":
			if index+1 >= len(args) {
				return options, nil, fmt.Errorf(auditUsage)
			}
			index++
			options.DiffPath = strings.TrimSpace(args[index])
			if options.DiffPath == "" {
				return options, nil, fmt.Errorf(auditUsage)
			}
		default:
			projectArgs = append(projectArgs, arg)
		}
	}
	return options, projectArgs, nil
}

func handleAuditTests(auditOptions auditCommandOptions, options cliOptions, ir gwdkir.Program, manifest securitymanifest.SecurityManifest) ([]auditspec.Finding, error) {
	if auditOptions.CheckTests {
		return checkStandaloneAuditTests(auditOptions, options, ir, manifest)
	}
	if !auditOptions.EmitTests && !auditOptions.RunTests {
		return nil, nil
	}

	if auditOptions.EmitTests {
		testPath := auditOptions.TestPath
		if !filepath.IsAbs(testPath) {
			testPath = filepath.Join(options.ProjectRoot, testPath)
		}
		packageName := standaloneAuditPackageName(filepath.Dir(testPath))
		source, err := appgen.StandaloneAuditTestSourceWithPackage(packageName, options.Config, manifest, ir.AuditSpecs)
		if err != nil {
			return nil, err
		}
		if len(source) == 0 {
			return nil, nil
		}
		source = generatedStandaloneAuditTestSource(source, manifest, relativizeAuditPolicies(auditspec.ComposeBaseline(auditspec.PoliciesFromIR(ir.AuditSpecs)), options.ProjectRoot))
		if err := os.MkdirAll(filepath.Dir(testPath), 0o755); err != nil {
			return nil, err
		}
		if err := writeStandaloneAuditTestFile(testPath, source, auditOptions.Force); err != nil {
			return nil, err
		}
		fmt.Fprintf(os.Stderr, "wrote audit tests: %s\n", testPath)
	}

	if !auditOptions.RunTests {
		return nil, nil
	}
	if customGuards := auditProgramCustomGuardIDs(ir); len(customGuards) > 0 {
		return []auditspec.Finding{{
			Code:        "audit_guard_unverified",
			Severity:    auditDiagnosticSeverity("audit_guard_unverified"),
			Target:      "runtime",
			Source:      "gowdk audit --run",
			Message:     fmt.Sprintf("generated audit integration tests require explicit fixtures for custom guards: %s", strings.Join(customGuards, ", ")),
			Remediation: "Add app-owned generated-app guard fixtures for these custom guards, or avoid claiming runtime verification for scenarios that depend on them.",
		}}, nil
	}

	runOptions := defaultAuditRunOptions()
	if auditOptions.RunTimeout > 0 {
		runOptions.Timeout = auditOptions.RunTimeout
	}

	testPath, result, err := runGeneratedAppAuditTests(options, ir, runOptions)
	if err != nil {
		return nil, err
	}
	if testPath == "" {
		// No generated audit tests exist for this program; nothing to run.
		return nil, nil
	}

	switch {
	case result.TimedOut:
		writeAuditRunOutput(result)
		fmt.Fprintf(os.Stderr, "audit generated app tests timed out after %s: %s\n", runOptions.Timeout, testPath)
		return []auditspec.Finding{{
			Code:        "audit_test_timeout",
			Severity:    auditDiagnosticSeverity("audit_test_timeout"),
			Target:      "runtime",
			Source:      testPath,
			Message:     fmt.Sprintf("generated audit integration tests timed out after %s", runOptions.Timeout),
			Remediation: "Investigate the hanging test, or raise the deadline with gowdk audit --run --run-timeout=<duration>.",
		}}, nil
	case result.ExitErr != nil:
		writeAuditRunOutput(result)
		message := "generated audit integration tests failed"
		if result.Truncated {
			message += " (output truncated)"
		}
		return []auditspec.Finding{{
			Code:        "audit_test_failed",
			Severity:    auditDiagnosticSeverity("audit_test_failed"),
			Target:      "runtime",
			Source:      testPath,
			Message:     message,
			Remediation: "Run gowdk audit --run locally, then update generated runtime behavior or policy expectations.",
		}}, nil
	default:
		fmt.Fprintf(os.Stderr, "audit generated app tests passed: %s\n", testPath)
		return nil, nil
	}
}

func standaloneAuditPackageName(dir string) string {
	packages, err := parser.ParseDir(token.NewFileSet(), dir, func(info os.FileInfo) bool {
		name := info.Name()
		return strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go")
	}, parser.PackageClauseOnly)
	if err != nil || len(packages) == 0 {
		return "gowdkaudit_test"
	}
	names := make([]string, 0, len(packages))
	for name := range packages {
		names = append(names, name)
	}
	sort.Strings(names)
	return names[0] + "_test"
}

// runGeneratedAppAuditTests builds and generates a throwaway app from the
// validated IR, then runs its audit test package under the bounded execution
// boundary in runAuditTestCommand. The returned testPath is empty when the
// program has no generated audit tests. A non-nil error reports an
// infrastructure failure (build or generation); test execution outcomes,
// including non-zero exit and timeout, are reported through auditRunResult.
func runGeneratedAppAuditTests(options cliOptions, ir gwdkir.Program, runOptions auditRunOptions) (string, auditRunResult, error) {
	source, err := appgen.GeneratedAuditTestSource(appgen.OptionsFromIR(options.Config, &ir))
	if err != nil || len(source) == 0 {
		return "", auditRunResult{}, err
	}

	tempRoot, err := os.MkdirTemp("", "gowdk-audit-run-*")
	if err != nil {
		return "", auditRunResult{}, err
	}
	defer os.RemoveAll(tempRoot)

	outputDir := filepath.Join(tempRoot, "output")
	appDir := filepath.Join(tempRoot, "app")
	if _, err := buildgen.BuildFromValidatedIR(options.Config, ir, outputDir); err != nil {
		return "", auditRunResult{}, err
	}
	app, err := appgen.GenerateWithOptions(outputDir, appDir, appgen.OptionsFromIR(options.Config, &ir))
	if err != nil {
		return "", auditRunResult{}, err
	}
	if err := writeGeneratedAppAuditRunHooks(app.AppDir, ir); err != nil {
		return "", auditRunResult{}, err
	}

	testPath := filepath.Join(app.AppDir, "gowdkapp", "gowdk_audit_test.go")
	result := runAuditTestCommand(context.Background(), app.AppDir, runOptions)
	return testPath, result, nil
}

func writeGeneratedAppAuditRunHooks(appDir string, ir gwdkir.Program) error {
	usesNativeRBAC := auditProgramUsesNativeRBACGuards(ir)
	if !usesNativeRBAC {
		return nil
	}
	hookPath := filepath.Join(appDir, "gowdkapp", "gowdk_audit_hooks_test.go")
	var builder strings.Builder
	builder.WriteString("package gowdkapp\n\n")
	builder.WriteString("import (\n")
	builder.WriteString("\t\"net/http\"\n")
	builder.WriteString("\t\"strings\"\n\n")
	builder.WriteString("\tgowdkauth \"github.com/cssbruno/gowdk/runtime/auth\"\n")
	builder.WriteString(")\n")

	builder.WriteString(`
func GOWDKAuthProvider() gowdkauth.Provider {
	return gowdkauth.ProviderFunc(func(request *http.Request) (*gowdkauth.Principal, error) {
		actor := strings.TrimSpace(request.Header.Get("X-GOWDK-Audit-Actor"))
		switch {
		case actor == "" || actor == "anonymous":
			return nil, nil
		case strings.HasPrefix(actor, "role:"):
			return &gowdkauth.Principal{ID: "audit", Roles: []string{strings.TrimPrefix(actor, "role:")}}, nil
		case strings.HasPrefix(actor, "permission:"):
			return &gowdkauth.Principal{ID: "audit", Permissions: []string{strings.TrimPrefix(actor, "permission:")}}, nil
		default:
			return &gowdkauth.Principal{ID: "audit", Roles: []string{actor}}, nil
		}
	})
}
`)
	return os.WriteFile(hookPath, []byte(builder.String()), 0o644)
}

func auditProgramUsesNativeRBACGuards(ir gwdkir.Program) bool {
	for _, page := range ir.Pages {
		if auditGuardsUseNativeRBAC(page.Guards) {
			return true
		}
	}
	for _, route := range ir.Routes {
		if auditGuardsUseNativeRBAC(route.Guards) {
			return true
		}
	}
	for _, endpoint := range ir.Endpoints {
		if auditGuardsUseNativeRBAC(endpoint.Guards) {
			return true
		}
	}
	for _, ref := range ir.ContractRefs {
		if auditGuardsUseNativeRBAC(ref.Guards) {
			return true
		}
	}
	return false
}

func auditProgramCustomGuardIDs(ir gwdkir.Program) []string {
	seen := map[string]bool{}
	var guards []string
	add := func(names []string) {
		for _, name := range names {
			name = strings.TrimSpace(name)
			if name == "" || name == "public" || auditGuardsUseNativeRBAC([]string{name}) || seen[name] {
				continue
			}
			seen[name] = true
			guards = append(guards, name)
		}
	}
	for _, page := range ir.Pages {
		add(page.Guards)
	}
	for _, route := range ir.Routes {
		add(route.Guards)
	}
	for _, endpoint := range ir.Endpoints {
		add(endpoint.Guards)
	}
	for _, ref := range ir.ContractRefs {
		add(ref.Guards)
	}
	sort.Strings(guards)
	return guards
}

func auditGuardsUseNativeRBAC(guards []string) bool {
	for _, guard := range guards {
		guard = strings.TrimSpace(guard)
		if strings.HasPrefix(guard, "role:") || strings.HasPrefix(guard, "permission:") {
			return true
		}
	}
	return false
}

// auditTestMetadata is the identity embedded in an emitted standalone audit test
// so CI (gowdk audit --check-tests) can detect when the checked-in file no longer
// matches the project. It pins the posture schema version, the compiler/tool
// version, and the policy and posture digests, so a route, guard, policy, schema,
// or compiler change makes the committed test detectably stale.
type auditTestMetadata struct {
	Version  int
	Schema   int
	Compiler string
	Tool     string
	Posture  string
	Policy   string
	Source   string
}

func auditTestMetadataFor(source []byte, manifest securitymanifest.SecurityManifest, policies []auditspec.Policy) auditTestMetadata {
	return auditTestMetadata{
		Version:  1,
		Schema:   securitymanifest.SchemaVersion,
		Compiler: version,
		Tool:     version,
		Posture:  auditPostureDigest(manifest),
		Policy:   auditPolicyDigest(policies),
		Source:   auditDigest(source),
	}
}

func (meta auditTestMetadata) line() string {
	return fmt.Sprintf(
		"%sversion=%d schema=%d compiler=%s tool=%s posture=%s policy=%s source=%s\n\n",
		auditGeneratedMetadataPrefix,
		meta.Version, meta.Schema, meta.Compiler, meta.Tool, meta.Posture, meta.Policy, meta.Source,
	)
}

// parseAuditTestMetadata extracts the identity line from an emitted audit test.
func parseAuditTestMetadata(payload []byte) (auditTestMetadata, bool) {
	prefix := strings.TrimSpace(auditGeneratedMetadataPrefix)
	for _, raw := range strings.Split(string(payload), "\n") {
		line := strings.TrimSpace(raw)
		if !strings.HasPrefix(line, prefix) {
			continue
		}
		meta := auditTestMetadata{}
		for _, field := range strings.Fields(strings.TrimSpace(strings.TrimPrefix(line, prefix))) {
			key, value, ok := strings.Cut(field, "=")
			if !ok {
				continue
			}
			switch key {
			case "version":
				meta.Version = atoiOrZero(value)
			case "schema":
				meta.Schema = atoiOrZero(value)
			case "compiler":
				meta.Compiler = value
			case "tool":
				meta.Tool = value
			case "posture":
				meta.Posture = value
			case "policy":
				meta.Policy = value
			case "source":
				meta.Source = value
			}
		}
		return meta, true
	}
	return auditTestMetadata{}, false
}

func atoiOrZero(value string) int {
	number := 0
	for _, char := range value {
		if char < '0' || char > '9' {
			return 0
		}
		number = number*10 + int(char-'0')
	}
	return number
}

// auditTestMetadataDiff reports the first identity field that drifted, or "" when
// the checked-in metadata still matches the freshly computed identity.
func auditTestMetadataDiff(got, want auditTestMetadata) string {
	switch {
	case got.Schema != want.Schema:
		return fmt.Sprintf("posture schema version changed (was %d, now %d)", got.Schema, want.Schema)
	case got.Compiler != want.Compiler:
		return fmt.Sprintf("compiler version changed (was %s, now %s)", emptyAsNone(got.Compiler), want.Compiler)
	case got.Posture != want.Posture:
		return "security posture changed"
	case got.Policy != want.Policy:
		return "audit policy changed"
	case got.Source != want.Source:
		return "generated test content changed"
	default:
		return ""
	}
}

func emptyAsNone(value string) string {
	if value == "" {
		return "<none>"
	}
	return value
}

func generatedStandaloneAuditTestSource(source []byte, manifest securitymanifest.SecurityManifest, policies []auditspec.Policy) []byte {
	metadata := auditTestMetadataFor(source, manifest, policies).line()
	out := make([]byte, 0, len(auditGeneratedMarker)+len(metadata)+len(source))
	out = append(out, auditGeneratedMarker...)
	out = append(out, metadata...)
	out = append(out, source...)
	return out
}

// checkStandaloneAuditTests is the CI verb behind gowdk audit --check-tests. It
// compares the checked-in generated audit test against the identity computed
// from the current posture and policies and reports audit_test_stale when they
// diverge, when the file is missing, or when it is not a generated test.
func checkStandaloneAuditTests(auditOptions auditCommandOptions, options cliOptions, ir gwdkir.Program, manifest securitymanifest.SecurityManifest) ([]auditspec.Finding, error) {
	testPath := auditOptions.TestPath
	if !filepath.IsAbs(testPath) {
		testPath = filepath.Join(options.ProjectRoot, testPath)
	}
	packageName := standaloneAuditPackageName(filepath.Dir(testPath))
	source, err := appgen.StandaloneAuditTestSourceWithPackage(packageName, options.Config, manifest, ir.AuditSpecs)
	if err != nil {
		return nil, err
	}
	policies := relativizeAuditPolicies(auditspec.ComposeBaseline(auditspec.PoliciesFromIR(ir.AuditSpecs)), options.ProjectRoot)

	existing, readErr := os.ReadFile(testPath)
	switch {
	case os.IsNotExist(readErr):
		if len(source) == 0 {
			return nil, nil
		}
		return []auditspec.Finding{staleAuditTestFinding(testPath,
			"no checked-in generated audit test was found for the current posture")}, nil
	case readErr != nil:
		return nil, readErr
	}
	if len(source) == 0 {
		return []auditspec.Finding{staleAuditTestFinding(testPath,
			"a generated audit test is checked in but the current posture generates none")}, nil
	}
	if !isStandaloneAuditGeneratedFile(existing) {
		return []auditspec.Finding{staleAuditTestFinding(testPath,
			"the checked-in file is not a gowdk-generated audit test")}, nil
	}
	got, ok := parseAuditTestMetadata(existing)
	if !ok {
		return []auditspec.Finding{staleAuditTestFinding(testPath,
			"the checked-in audit test carries no identity metadata")}, nil
	}
	body, extracted := standaloneAuditTestBody(existing)
	if !extracted {
		return []auditspec.Finding{staleAuditTestFinding(testPath,
			"the checked-in audit test is missing its generated header")}, nil
	}
	// Verify the actual checked-in body against the freshly generated body, not
	// just the recorded identity line: a generated test can be hand-edited while
	// leaving the metadata header (and its source= digest) intact, which a
	// header-only comparison would miss. Trusting the embedded digest would let a
	// tampered body pass, so the live body digest replaces it before comparison.
	got.Source = auditDigest(body)
	if diff := auditTestMetadataDiff(got, auditTestMetadataFor(source, manifest, policies)); diff != "" {
		return []auditspec.Finding{staleAuditTestFinding(testPath, diff)}, nil
	}
	return nil, nil
}

// standaloneAuditTestBody recovers the generated source body from an emitted
// audit test by stripping the generated marker and the identity metadata line,
// exactly inverting generatedStandaloneAuditTestSource. It returns false when
// the header is absent so the caller can report the file as not generated.
func standaloneAuditTestBody(payload []byte) ([]byte, bool) {
	if !bytes.HasPrefix(payload, []byte(auditGeneratedMarker)) {
		return nil, false
	}
	rest := payload[len(auditGeneratedMarker):]
	if !bytes.HasPrefix(rest, []byte(auditGeneratedMetadataPrefix)) {
		return nil, false
	}
	sep := bytes.Index(rest, []byte("\n\n"))
	if sep < 0 {
		return nil, false
	}
	return rest[sep+2:], true
}

func staleAuditTestFinding(testPath, reason string) auditspec.Finding {
	return auditspec.Finding{
		Code:        "audit_test_stale",
		Severity:    auditDiagnosticSeverity("audit_test_stale"),
		Target:      "generated-audit-test",
		Source:      filepath.ToSlash(testPath),
		Message:     "checked-in generated audit test is stale: " + reason,
		Remediation: "Run gowdk audit --emit-tests to regenerate the test and commit the result.",
	}
}

func writeStandaloneAuditTestFile(testPath string, source []byte, force bool) error {
	existing, err := os.ReadFile(testPath)
	switch {
	case err == nil:
		if !force && !isStandaloneAuditGeneratedFile(existing) {
			return fmt.Errorf("%s already exists and is not a gowdk-generated audit test; rerun with --force to overwrite", testPath)
		}
	case os.IsNotExist(err):
		// New generated audit test file.
	default:
		return err
	}

	temp, err := os.CreateTemp(filepath.Dir(testPath), ".gowdk-audit-*.tmp")
	if err != nil {
		return err
	}
	tempPath := temp.Name()
	removeTemp := true
	defer func() {
		if removeTemp {
			_ = os.Remove(tempPath)
		}
	}()
	if _, err := temp.Write(source); err != nil {
		_ = temp.Close()
		return err
	}
	if err := temp.Chmod(0o644); err != nil {
		_ = temp.Close()
		return err
	}
	if err := temp.Close(); err != nil {
		return err
	}
	if err := os.Rename(tempPath, testPath); err != nil {
		return err
	}
	removeTemp = false
	return nil
}

func isStandaloneAuditGeneratedFile(payload []byte) bool {
	return bytes.HasPrefix(payload, []byte(auditGeneratedMarker)) &&
		bytes.Contains(payload, []byte(auditGeneratedMetadataPrefix))
}

// writeAuditRunOutput prints the bounded test output to stderr, followed by an
// explicit truncation marker when the output exceeded the capture limit.
func writeAuditRunOutput(result auditRunResult) {
	if output := strings.TrimSpace(result.Output); output != "" {
		fmt.Fprintln(os.Stderr, output)
	}
	if result.Truncated {
		fmt.Fprintln(os.Stderr, auditRunTruncationMarker)
	}
}

func auditDiagnosticSeverity(code string) diagnostics.Severity {
	if severity, ok := diagnostics.DefaultSeverity(code); ok {
		return severity
	}
	return diagnostics.SeverityError
}

func buildAuditReport(options cliOptions, manifest securitymanifest.SecurityManifest, findings []auditspec.Finding, policies []auditspec.Policy) auditReport {
	summary := auditspec.Summarize(findings)
	if findings == nil {
		findings = []auditspec.Finding{}
	}
	buildMode := auditBuildMode(options.Config)
	return auditReport{
		Version:       1,
		Schema:        "gowdk.audit.report.v1",
		Tool:          auditToolMetadata{Name: "gowdk audit", Version: version},
		PolicyDigest:  auditPolicyDigest(policies),
		PostureDigest: auditPostureDigest(manifest),
		BuildMode:     buildMode,
		Target:        auditTargetMetadata{BuildMode: buildMode},
		History:       auditHistoryMetadata{Mode: "not-tracked"},
		Status:        auditspec.Status(summary),
		Summary: auditSummary{
			Routes:    len(manifest.Routes),
			Endpoints: len(manifest.Endpoints),
			Contracts: len(manifest.Contracts),
			Errors:    summary.Errors,
			Warnings:  summary.Warnings,
			Info:      summary.Info,
			Waived:    summary.Waived,
		},
		Posture:  auditPostureFor(manifest),
		Waivers:  auditWaiverRecords(findings),
		Findings: findings,
		Manifest: manifest,
	}
}

// auditWaiverRecords derives the applied-waiver provenance from the suppressed
// findings so the JSON report lists every active suppression.
func auditWaiverRecords(findings []auditspec.Finding) []auditWaiverRecord {
	var records []auditWaiverRecord
	for _, finding := range findings {
		if finding.Suppression == nil {
			continue
		}
		records = append(records, auditWaiverRecord{
			Code:          finding.Code,
			Target:        finding.Target,
			Owner:         finding.Suppression.Owner,
			Justification: finding.Suppression.Justification,
			Expires:       finding.Suppression.Expires,
			Ticket:        finding.Suppression.Ticket,
			DigestScope:   finding.Suppression.DigestScope,
			Source:        finding.Source,
		})
	}
	return records
}

func auditPostureFor(manifest securitymanifest.SecurityManifest) auditPostureSummary {
	posture := auditPostureSummary{Evidence: map[string]int{}}
	for _, obligation := range manifest.Obligations {
		posture.Obligations++
		posture.Evidence[string(obligation.Evidence)]++
		if obligation.Evidence == securitymanifest.EvidenceUnverifiedAppOwned {
			posture.UnverifiedAppOwned++
		}
	}
	return posture
}

// auditEvidenceOrder lists the evidence states in a stable display order so the
// human report is deterministic regardless of map iteration order.
var auditEvidenceOrder = []securitymanifest.EvidenceState{
	securitymanifest.EvidenceVerifiedStatic,
	securitymanifest.EvidenceVerifiedRuntime,
	securitymanifest.EvidenceDeclared,
	securitymanifest.EvidenceUnverifiedAppOwned,
	securitymanifest.EvidenceNotApplicable,
	securitymanifest.EvidenceWaived,
}

func formatAuditEvidenceCounts(counts map[string]int) string {
	parts := make([]string, 0, len(counts))
	for _, state := range auditEvidenceOrder {
		if n := counts[string(state)]; n > 0 {
			parts = append(parts, fmt.Sprintf("%s: %d", state, n))
		}
	}
	return strings.Join(parts, ", ")
}

func auditBuildMode(config gowdk.Config) string {
	mode := strings.TrimSpace(string(config.Build.Mode))
	if mode == "" {
		return string(gowdk.Development)
	}
	return mode
}

func auditDigest(value any) string {
	payload, err := json.Marshal(value)
	if err != nil {
		payload = []byte(fmt.Sprintf("%#v", value))
	}
	sum := sha256.Sum256(payload)
	return fmt.Sprintf("sha256:%x", sum[:])
}

// auditPostureDigest hashes the posture a waiver pins. Declared waivers are
// excluded so adding or editing a waiver (recorded in gowdk-security.json) does
// not change the posture digest the waiver itself pins, which would otherwise be
// self-referential.
func auditPostureDigest(manifest securitymanifest.SecurityManifest) string {
	manifest.Waivers = nil
	return auditDigest(manifest)
}

// auditPolicyDigest hashes the policy set a waiver pins. waive rules are stripped
// so the digest reflects the enforcement rules (baseline plus declared
// tightening) and stays stable when waivers are added or edited. A policy left
// with no enforcement rules after stripping (a waiver-only `policy { waive ... }`
// block, or an otherwise empty policy) is dropped entirely, so declaring a waiver
// policy does not shift the digest and falsely mark digest-pinned waivers or
// committed audit tests as stale.
func auditPolicyDigest(policies []auditspec.Policy) string {
	stripped := make([]auditspec.Policy, 0, len(policies))
	for _, policy := range policies {
		var rules []auditspec.Rule
		for _, rule := range policy.Rules {
			if rule.Kind == auditspec.RuleWaive {
				continue
			}
			rules = append(rules, rule)
		}
		if len(rules) == 0 {
			continue
		}
		policy.Rules = rules
		stripped = append(stripped, policy)
	}
	return auditDigest(stripped)
}

// relativizeAuditPolicies returns the policies with their declaration source and
// per-rule sources rewritten relative to root, so the policy digest and
// policy-resolution findings are identical regardless of checkout location.
// Built-in baseline policies carry no file source and pass through unchanged.
func relativizeAuditPolicies(policies []auditspec.Policy, root string) []auditspec.Policy {
	if strings.TrimSpace(root) == "" || len(policies) == 0 {
		return policies
	}
	out := make([]auditspec.Policy, len(policies))
	for index, policy := range policies {
		policy.Source = securitymanifest.RelativizeSourceRef(policy.Source, root)
		if len(policy.Rules) > 0 {
			rules := append([]auditspec.Rule(nil), policy.Rules...)
			for ruleIndex := range rules {
				rules[ruleIndex].Source = securitymanifest.RelativizeSourceRef(rules[ruleIndex].Source, root)
			}
			policy.Rules = rules
		}
		out[index] = policy
	}
	return out
}

func printAuditReport(report auditReport) {
	fmt.Printf("GOWDK audit: %s\n", strings.ToUpper(report.Status))
	fmt.Printf("Posture: %d route(s), %d endpoint(s), %d contract(s)\n", report.Summary.Routes, report.Summary.Endpoints, report.Summary.Contracts)
	if report.Posture.Obligations > 0 {
		fmt.Printf("Obligations: %d (%s)\n", report.Posture.Obligations, formatAuditEvidenceCounts(report.Posture.Evidence))
		if report.Posture.UnverifiedAppOwned > 0 {
			fmt.Printf("  %d app-owned obligation(s) cannot be statically verified by gowdk; record app-owned evidence (see docs/engineering/security.md).\n", report.Posture.UnverifiedAppOwned)
		}
	}
	fmt.Printf("Findings: %d error(s), %d warning(s), %d info\n", report.Summary.Errors, report.Summary.Warnings, report.Summary.Info)
	if report.Diff != nil {
		fmt.Printf("Diff vs %s: %d introduced (%d error, %d warning), %d resolved, %d unchanged\n",
			report.Diff.Baseline,
			len(report.Diff.Introduced), report.Diff.IntroducedErrors, report.Diff.IntroducedWarnings,
			len(report.Diff.Resolved), report.Diff.Unchanged)
		if report.Diff.IntroducedErrors == 0 {
			fmt.Println("  No newly introduced error findings since the baseline report.")
		}
	}
	if report.Summary.Waived > 0 {
		fmt.Printf("Waived: %d finding(s) suppressed by explicit waiver\n", report.Summary.Waived)
		for _, waiver := range report.Waivers {
			fmt.Printf("  - %s on %s by %s until %s (%s)\n", waiver.Code, waiver.Target, waiver.Owner, waiver.Expires, waiver.Justification)
		}
	}
	if len(report.Findings) == 0 {
		fmt.Println("No policy findings. Posture matches the security baseline.")
		return
	}
	for _, finding := range report.Findings {
		if finding.Suppression != nil {
			// Waived findings are listed under the Waived summary above.
			continue
		}
		location := finding.Target
		if finding.Source != "" {
			location = finding.Source
		}
		fmt.Printf("[%s] %s: %s\n", strings.ToUpper(string(finding.Severity)), finding.Code, finding.Message)
		if finding.CodeSource != "" {
			fmt.Printf("  code: %s (severity %s, source: %s)\n", finding.Code, finding.Severity, finding.CodeSource)
		}
		if location != "" {
			fmt.Printf("  at: %s\n", location)
		}
		if finding.Evidence != "" {
			fmt.Printf("  evidence: %s\n", finding.Evidence)
		}
		if finding.Remediation != "" {
			fmt.Printf("  fix: %s\n", finding.Remediation)
		}
		fmt.Printf("  why: gowdk explain %s\n", finding.Code)
	}
}
