package main

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/cssbruno/gowdk"
	"github.com/cssbruno/gowdk/internal/appgen"
	"github.com/cssbruno/gowdk/internal/auditspec"
	"github.com/cssbruno/gowdk/internal/buildgen"
	"github.com/cssbruno/gowdk/internal/diagnostics"
	"github.com/cssbruno/gowdk/internal/gwdkir"
	"github.com/cssbruno/gowdk/internal/lang"
	"github.com/cssbruno/gowdk/internal/securitymanifest"
)

const auditUsage = "usage: gowdk audit [--config <file>] [--env-file <file>] [--module <name>] [--ssr] [--json] [--emit-tests[=<file>]] [--force] [--run] [--run-timeout=<duration>] [files...]"

const (
	auditGeneratedMarker         = "// Code generated by gowdk audit --emit-tests; DO NOT EDIT.\n"
	auditGeneratedMetadataPrefix = "// gowdk:audit-generated "
)

// auditReport is the gowdk audit result: the derived security posture plus the
// findings from evaluating the built-in baseline and declared policies against
// it.
type auditReport struct {
	Version       int                               `json:"version"`
	Schema        string                            `json:"schema"`
	Tool          auditToolMetadata                 `json:"tool"`
	PolicyDigest  string                            `json:"policyDigest"`
	PostureDigest string                            `json:"postureDigest"`
	BuildMode     string                            `json:"buildMode"`
	Target        auditTargetMetadata               `json:"target"`
	History       auditHistoryMetadata              `json:"history"`
	Status        string                            `json:"status"`
	Summary       auditSummary                      `json:"summary"`
	Findings      []auditspec.Finding               `json:"findings"`
	Manifest      securitymanifest.SecurityManifest `json:"manifest"`
}

type auditToolMetadata struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

type auditTargetMetadata struct {
	BuildMode string `json:"buildMode"`
}

type auditHistoryMetadata struct {
	Mode string `json:"mode"`
}

type auditSummary struct {
	Routes    int `json:"routes"`
	Endpoints int `json:"endpoints"`
	Contracts int `json:"contracts"`
	Errors    int `json:"errors"`
	Warnings  int `json:"warnings"`
	Info      int `json:"info"`
}

type auditCommandOptions struct {
	EmitTests  bool
	RunTests   bool
	Force      bool
	TestPath   string
	RunTimeout time.Duration
}

type auditExitError struct {
	errors int
}

func (err auditExitError) Error() string {
	return fmt.Sprintf("audit found %d error finding(s)", err.errors)
}

func (auditExitError) SilentCLIError() {}

// audit derives the security posture from validated IR, evaluates the baseline
// policy against it, and reports findings. It is the full report surface
// (posture JSON, declared policies, optional runtime tests) and exits non-zero
// when any error-severity finding exists so it can gate CI. gowdk build runs the
// same baseline as a production gate (see enforceBuildSecurityAudit); this
// command stays available for explicit reports and non-production checks.
func audit(args []string) error {
	auditOptions, projectArgs, err := parseAuditCommandOptions(args)
	if err != nil {
		return err
	}
	options, paths, err := loadCommandInputs(projectArgs, "audit", true)
	if err != nil {
		return err
	}

	checked, diagnostics := lang.CheckFilesWithOptions(options.Config, paths, lang.CheckOptions{ProjectRoot: options.ProjectRoot})
	for _, diagnostic := range diagnostics {
		fmt.Fprintln(os.Stderr, diagnostic.String())
	}
	if diagnostics.HasErrors() {
		return fmt.Errorf("audit failed: source has validation errors")
	}

	ir := checked.IR
	if err := linkIRContractReferences(&ir, options.ProjectRoot); err != nil {
		return err
	}

	manifest := securitymanifest.Build(options.Config, ir)
	declared := auditspec.PoliciesFromIR(ir.AuditSpecs)
	policies := auditspec.ComposeBaseline(declared)
	findings := auditspec.Evaluate(manifest, policies)
	testFindings, err := handleAuditTests(auditOptions, options, ir, manifest)
	if err != nil {
		return err
	}
	findings = append(findings, testFindings...)
	findings = auditspec.EnrichFindings(findings)
	auditspec.SortFindings(findings)
	report := buildAuditReport(options, manifest, findings, policies)

	if options.JSON {
		payload, err := json.MarshalIndent(report, "", "  ")
		if err != nil {
			return err
		}
		fmt.Println(string(payload))
	} else {
		printAuditReport(report)
	}

	if report.Summary.Errors > 0 {
		return auditExitError{errors: report.Summary.Errors}
	}
	return nil
}

func parseAuditCommandOptions(args []string) (auditCommandOptions, []string, error) {
	options := auditCommandOptions{TestPath: "gowdk_audit_test.go"}
	var projectArgs []string
	for _, arg := range args {
		switch {
		case arg == "--emit-tests":
			options.EmitTests = true
		case strings.HasPrefix(arg, "--emit-tests="):
			options.EmitTests = true
			options.TestPath = strings.TrimSpace(strings.TrimPrefix(arg, "--emit-tests="))
			if options.TestPath == "" {
				return options, nil, fmt.Errorf(auditUsage)
			}
		case arg == "--force":
			options.Force = true
		case arg == "--run":
			options.RunTests = true
		case strings.HasPrefix(arg, "--run-timeout="):
			value := strings.TrimSpace(strings.TrimPrefix(arg, "--run-timeout="))
			duration, err := time.ParseDuration(value)
			if err != nil {
				return options, nil, fmt.Errorf("invalid --run-timeout %q: %w", value, err)
			}
			if duration <= 0 {
				return options, nil, fmt.Errorf("invalid --run-timeout %q: must be positive", value)
			}
			options.RunTimeout = duration
		default:
			projectArgs = append(projectArgs, arg)
		}
	}
	return options, projectArgs, nil
}

func handleAuditTests(auditOptions auditCommandOptions, options cliOptions, ir gwdkir.Program, manifest securitymanifest.SecurityManifest) ([]auditspec.Finding, error) {
	if !auditOptions.EmitTests && !auditOptions.RunTests {
		return nil, nil
	}

	if auditOptions.EmitTests {
		testPath := auditOptions.TestPath
		if !filepath.IsAbs(testPath) {
			testPath = filepath.Join(options.ProjectRoot, testPath)
		}
		packageName := standaloneAuditPackageName(filepath.Dir(testPath))
		source, err := appgen.StandaloneAuditTestSourceWithPackage(packageName, options.Config, manifest, ir.AuditSpecs)
		if err != nil {
			return nil, err
		}
		if len(source) == 0 {
			return nil, nil
		}
		source = generatedStandaloneAuditTestSource(source, manifest, auditspec.ComposeBaseline(auditspec.PoliciesFromIR(ir.AuditSpecs)))
		if err := os.MkdirAll(filepath.Dir(testPath), 0o755); err != nil {
			return nil, err
		}
		if err := writeStandaloneAuditTestFile(testPath, source, auditOptions.Force); err != nil {
			return nil, err
		}
		fmt.Fprintf(os.Stderr, "wrote audit tests: %s\n", testPath)
	}

	if !auditOptions.RunTests {
		return nil, nil
	}
	if customGuards := auditProgramCustomGuardIDs(ir); len(customGuards) > 0 {
		return []auditspec.Finding{{
			Code:        "audit_guard_unverified",
			Severity:    auditDiagnosticSeverity("audit_guard_unverified"),
			Target:      "runtime",
			Source:      "gowdk audit --run",
			Message:     fmt.Sprintf("generated audit integration tests require explicit fixtures for custom guards: %s", strings.Join(customGuards, ", ")),
			Remediation: "Add app-owned generated-app guard fixtures for these custom guards, or avoid claiming runtime verification for scenarios that depend on them.",
		}}, nil
	}

	runOptions := defaultAuditRunOptions()
	if auditOptions.RunTimeout > 0 {
		runOptions.Timeout = auditOptions.RunTimeout
	}

	testPath, result, err := runGeneratedAppAuditTests(options, ir, runOptions)
	if err != nil {
		return nil, err
	}
	if testPath == "" {
		// No generated audit tests exist for this program; nothing to run.
		return nil, nil
	}

	switch {
	case result.TimedOut:
		writeAuditRunOutput(result)
		fmt.Fprintf(os.Stderr, "audit generated app tests timed out after %s: %s\n", runOptions.Timeout, testPath)
		return []auditspec.Finding{{
			Code:        "audit_test_timeout",
			Severity:    auditDiagnosticSeverity("audit_test_timeout"),
			Target:      "runtime",
			Source:      testPath,
			Message:     fmt.Sprintf("generated audit integration tests timed out after %s", runOptions.Timeout),
			Remediation: "Investigate the hanging test, or raise the deadline with gowdk audit --run --run-timeout=<duration>.",
		}}, nil
	case result.ExitErr != nil:
		writeAuditRunOutput(result)
		message := "generated audit integration tests failed"
		if result.Truncated {
			message += " (output truncated)"
		}
		return []auditspec.Finding{{
			Code:        "audit_test_failed",
			Severity:    auditDiagnosticSeverity("audit_test_failed"),
			Target:      "runtime",
			Source:      testPath,
			Message:     message,
			Remediation: "Run gowdk audit --run locally, then update generated runtime behavior or policy expectations.",
		}}, nil
	default:
		fmt.Fprintf(os.Stderr, "audit generated app tests passed: %s\n", testPath)
		return nil, nil
	}
}

func standaloneAuditPackageName(dir string) string {
	packages, err := parser.ParseDir(token.NewFileSet(), dir, func(info os.FileInfo) bool {
		name := info.Name()
		return strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go")
	}, parser.PackageClauseOnly)
	if err != nil || len(packages) == 0 {
		return "gowdkaudit_test"
	}
	names := make([]string, 0, len(packages))
	for name := range packages {
		names = append(names, name)
	}
	sort.Strings(names)
	return names[0] + "_test"
}

// runGeneratedAppAuditTests builds and generates a throwaway app from the
// validated IR, then runs its audit test package under the bounded execution
// boundary in runAuditTestCommand. The returned testPath is empty when the
// program has no generated audit tests. A non-nil error reports an
// infrastructure failure (build or generation); test execution outcomes,
// including non-zero exit and timeout, are reported through auditRunResult.
func runGeneratedAppAuditTests(options cliOptions, ir gwdkir.Program, runOptions auditRunOptions) (string, auditRunResult, error) {
	source, err := appgen.GeneratedAuditTestSource(appgen.OptionsFromIR(options.Config, &ir))
	if err != nil || len(source) == 0 {
		return "", auditRunResult{}, err
	}

	tempRoot, err := os.MkdirTemp("", "gowdk-audit-run-*")
	if err != nil {
		return "", auditRunResult{}, err
	}
	defer os.RemoveAll(tempRoot)

	outputDir := filepath.Join(tempRoot, "output")
	appDir := filepath.Join(tempRoot, "app")
	if _, err := buildgen.BuildFromValidatedIR(options.Config, ir, outputDir); err != nil {
		return "", auditRunResult{}, err
	}
	app, err := appgen.GenerateWithOptions(outputDir, appDir, appgen.OptionsFromIR(options.Config, &ir))
	if err != nil {
		return "", auditRunResult{}, err
	}
	if err := writeGeneratedAppAuditRunHooks(app.AppDir, ir); err != nil {
		return "", auditRunResult{}, err
	}

	testPath := filepath.Join(app.AppDir, "gowdkapp", "gowdk_audit_test.go")
	result := runAuditTestCommand(context.Background(), app.AppDir, runOptions)
	return testPath, result, nil
}

func writeGeneratedAppAuditRunHooks(appDir string, ir gwdkir.Program) error {
	usesNativeRBAC := auditProgramUsesNativeRBACGuards(ir)
	if !usesNativeRBAC {
		return nil
	}
	hookPath := filepath.Join(appDir, "gowdkapp", "gowdk_audit_hooks_test.go")
	var builder strings.Builder
	builder.WriteString("package gowdkapp\n\n")
	builder.WriteString("import (\n")
	builder.WriteString("\t\"net/http\"\n")
	builder.WriteString("\t\"strings\"\n\n")
	builder.WriteString("\tgowdkauth \"github.com/cssbruno/gowdk/runtime/auth\"\n")
	builder.WriteString(")\n")

	builder.WriteString(`
func GOWDKAuthProvider() gowdkauth.Provider {
	return gowdkauth.ProviderFunc(func(request *http.Request) (*gowdkauth.Principal, error) {
		actor := strings.TrimSpace(request.Header.Get("X-GOWDK-Audit-Actor"))
		switch {
		case actor == "" || actor == "anonymous":
			return nil, nil
		case strings.HasPrefix(actor, "role:"):
			return &gowdkauth.Principal{ID: "audit", Roles: []string{strings.TrimPrefix(actor, "role:")}}, nil
		case strings.HasPrefix(actor, "permission:"):
			return &gowdkauth.Principal{ID: "audit", Permissions: []string{strings.TrimPrefix(actor, "permission:")}}, nil
		default:
			return &gowdkauth.Principal{ID: "audit", Roles: []string{actor}}, nil
		}
	})
}
`)
	return os.WriteFile(hookPath, []byte(builder.String()), 0o644)
}

func auditProgramUsesNativeRBACGuards(ir gwdkir.Program) bool {
	for _, page := range ir.Pages {
		if auditGuardsUseNativeRBAC(page.Guards) {
			return true
		}
	}
	for _, route := range ir.Routes {
		if auditGuardsUseNativeRBAC(route.Guards) {
			return true
		}
	}
	for _, endpoint := range ir.Endpoints {
		if auditGuardsUseNativeRBAC(endpoint.Guards) {
			return true
		}
	}
	for _, ref := range ir.ContractRefs {
		if auditGuardsUseNativeRBAC(ref.Guards) {
			return true
		}
	}
	return false
}

func auditProgramCustomGuardIDs(ir gwdkir.Program) []string {
	seen := map[string]bool{}
	var guards []string
	add := func(names []string) {
		for _, name := range names {
			name = strings.TrimSpace(name)
			if name == "" || name == "public" || auditGuardsUseNativeRBAC([]string{name}) || seen[name] {
				continue
			}
			seen[name] = true
			guards = append(guards, name)
		}
	}
	for _, page := range ir.Pages {
		add(page.Guards)
	}
	for _, route := range ir.Routes {
		add(route.Guards)
	}
	for _, endpoint := range ir.Endpoints {
		add(endpoint.Guards)
	}
	for _, ref := range ir.ContractRefs {
		add(ref.Guards)
	}
	sort.Strings(guards)
	return guards
}

func auditGuardsUseNativeRBAC(guards []string) bool {
	for _, guard := range guards {
		guard = strings.TrimSpace(guard)
		if strings.HasPrefix(guard, "role:") || strings.HasPrefix(guard, "permission:") {
			return true
		}
	}
	return false
}

func generatedStandaloneAuditTestSource(source []byte, manifest securitymanifest.SecurityManifest, policies []auditspec.Policy) []byte {
	metadata := fmt.Sprintf(
		"%sversion=1 tool=%s posture=%s policy=%s source=%s\n\n",
		auditGeneratedMetadataPrefix,
		version,
		auditDigest(manifest),
		auditDigest(policies),
		auditDigest(source),
	)
	out := make([]byte, 0, len(auditGeneratedMarker)+len(metadata)+len(source))
	out = append(out, auditGeneratedMarker...)
	out = append(out, metadata...)
	out = append(out, source...)
	return out
}

func writeStandaloneAuditTestFile(testPath string, source []byte, force bool) error {
	existing, err := os.ReadFile(testPath)
	switch {
	case err == nil:
		if !force && !isStandaloneAuditGeneratedFile(existing) {
			return fmt.Errorf("%s already exists and is not a gowdk-generated audit test; rerun with --force to overwrite", testPath)
		}
	case os.IsNotExist(err):
		// New generated audit test file.
	default:
		return err
	}

	temp, err := os.CreateTemp(filepath.Dir(testPath), ".gowdk-audit-*.tmp")
	if err != nil {
		return err
	}
	tempPath := temp.Name()
	removeTemp := true
	defer func() {
		if removeTemp {
			_ = os.Remove(tempPath)
		}
	}()
	if _, err := temp.Write(source); err != nil {
		_ = temp.Close()
		return err
	}
	if err := temp.Chmod(0o644); err != nil {
		_ = temp.Close()
		return err
	}
	if err := temp.Close(); err != nil {
		return err
	}
	if err := os.Rename(tempPath, testPath); err != nil {
		return err
	}
	removeTemp = false
	return nil
}

func isStandaloneAuditGeneratedFile(payload []byte) bool {
	return bytes.HasPrefix(payload, []byte(auditGeneratedMarker)) &&
		bytes.Contains(payload, []byte(auditGeneratedMetadataPrefix))
}

// writeAuditRunOutput prints the bounded test output to stderr, followed by an
// explicit truncation marker when the output exceeded the capture limit.
func writeAuditRunOutput(result auditRunResult) {
	if output := strings.TrimSpace(result.Output); output != "" {
		fmt.Fprintln(os.Stderr, output)
	}
	if result.Truncated {
		fmt.Fprintln(os.Stderr, auditRunTruncationMarker)
	}
}

func auditDiagnosticSeverity(code string) diagnostics.Severity {
	if severity, ok := diagnostics.DefaultSeverity(code); ok {
		return severity
	}
	return diagnostics.SeverityError
}

func buildAuditReport(options cliOptions, manifest securitymanifest.SecurityManifest, findings []auditspec.Finding, policies []auditspec.Policy) auditReport {
	summary := auditspec.Summarize(findings)
	if findings == nil {
		findings = []auditspec.Finding{}
	}
	buildMode := auditBuildMode(options.Config)
	return auditReport{
		Version:       1,
		Schema:        "gowdk.audit.report.v1",
		Tool:          auditToolMetadata{Name: "gowdk audit", Version: version},
		PolicyDigest:  auditDigest(policies),
		PostureDigest: auditDigest(manifest),
		BuildMode:     buildMode,
		Target:        auditTargetMetadata{BuildMode: buildMode},
		History:       auditHistoryMetadata{Mode: "not-tracked"},
		Status:        auditspec.Status(summary),
		Summary: auditSummary{
			Routes:    len(manifest.Routes),
			Endpoints: len(manifest.Endpoints),
			Contracts: len(manifest.Contracts),
			Errors:    summary.Errors,
			Warnings:  summary.Warnings,
			Info:      summary.Info,
		},
		Findings: findings,
		Manifest: manifest,
	}
}

func auditBuildMode(config gowdk.Config) string {
	mode := strings.TrimSpace(string(config.Build.Mode))
	if mode == "" {
		return string(gowdk.Development)
	}
	return mode
}

func auditDigest(value any) string {
	payload, err := json.Marshal(value)
	if err != nil {
		payload = []byte(fmt.Sprintf("%#v", value))
	}
	sum := sha256.Sum256(payload)
	return fmt.Sprintf("sha256:%x", sum[:])
}

func printAuditReport(report auditReport) {
	fmt.Printf("GOWDK audit: %s\n", strings.ToUpper(report.Status))
	fmt.Printf("Posture: %d route(s), %d endpoint(s), %d contract(s)\n", report.Summary.Routes, report.Summary.Endpoints, report.Summary.Contracts)
	fmt.Printf("Findings: %d error(s), %d warning(s), %d info\n", report.Summary.Errors, report.Summary.Warnings, report.Summary.Info)
	if len(report.Findings) == 0 {
		fmt.Println("No policy findings. Posture matches the security baseline.")
		return
	}
	for _, finding := range report.Findings {
		location := finding.Target
		if finding.Source != "" {
			location = finding.Source
		}
		fmt.Printf("[%s] %s: %s\n", strings.ToUpper(string(finding.Severity)), finding.Code, finding.Message)
		if finding.CodeSource != "" {
			fmt.Printf("  code: %s (severity %s, source: %s)\n", finding.Code, finding.Severity, finding.CodeSource)
		}
		if location != "" {
			fmt.Printf("  at: %s\n", location)
		}
		if finding.Remediation != "" {
			fmt.Printf("  fix: %s\n", finding.Remediation)
		}
		fmt.Printf("  why: gowdk explain %s\n", finding.Code)
	}
}
